import type { TransactionInput } from './domain.js';
export const synthetic: TransactionInput[] = [
  {
    source: 'synthetic',
    sourceId: 'demo-1',
    accountId: 'rodion-uah',
    owner: 'rodion',
    bookedAt: '2026-09-01T10:00:00.000Z',
    currency: 'UAH',
    amountMinor: '-128050',
    description: 'Groceries — example',
  },
  {
    source: 'synthetic',
    sourceId: 'demo-2',
    accountId: 'katya-uah',
    owner: 'katya',
    bookedAt: '2026-09-02T10:00:00.000Z',
    currency: 'UAH',
    amountMinor: '-45000',
    description: 'Parcel payment — needs clarification',
  },
  {
    source: 'synthetic',
    sourceId: 'demo-3',
    accountId: 'rodion-uah',
    owner: 'rodion',
    bookedAt: '2026-09-03T10:00:00.000Z',
    currency: 'UAH',
    amountMinor: '-100000',
    description: 'Transfer to Katya — example',
  },
  {
    source: 'synthetic',
    sourceId: 'demo-4',
    accountId: 'katya-uah',
    owner: 'katya',
    bookedAt: '2026-09-03T10:01:00.000Z',
    currency: 'UAH',
    amountMinor: '100000',
    description: 'Transfer from Rodion — example',
  },
  {
    source: 'synthetic',
    sourceId: 'demo-5',
    accountId: 'rodion-eur',
    owner: 'rodion',
    bookedAt: '2026-09-04T10:00:00.000Z',
    currency: 'EUR',
    amountMinor: '-3250',
    description: 'Dinner — example',
  },
];
